route:
 repeat_interval: 1h
 receiver: default
 routes:
   - receiver: 'slack-demo'
     match:
       severity: page

receivers:
 - name: default
 - name: slack-demo
   slack_configs:
   - api_url: "https://hooks.slack.com/services/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"
     channel: "#talk-jamie-wilkinson"
